- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://packages.cloud.google.com/apt coral-edgetpu-stable main
    state: present
- name: Update repositories cache and install "libedgetpu1-std" package
  ansible.builtin.apt:
    name: libedgetpu1-std
    update_cache: yes