---
- hosts: k3s_cluster
  gather_facts: yes
  roles:
    - role: prereq
      become: true
    - role: download
      become: true
    - role: raspberrypi
      become: true

- hosts: ai_accelerator
  roles:
    - role: coral
      become: true

- hosts: storage_server
  roles:
    - role: nfs-server
      become: true

- hosts: storage_client
  roles:
    - role: nfs-client
      become: true
    - role: iscsi-client
      become: true

- hosts: master
  roles:
    - role: k3s/master
      become: true

- hosts: node
  roles:
    - role: k3s/node
      become: true

- hosts: master
  roles:
    - role: k3s/post
      become: true
